# Generated by Django 5.1.4 on 2025-06-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_achat", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en attente", "En attente"),
                            ("en cours", "En cours"),
                            ("livrée", "Livrée"),
                            ("annulée", "Annulée"),
                        ],
                        default="en attente",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_commande", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en attente", "En attente"),
                            ("en cours", "En cours"),
                            ("livrée", "Livrée"),
                            ("annulée", "Annulée"),
                        ],
                        default="en attente",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_banque", models.CharField(max_length=100)),
                ("numero_compte", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigurationERP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utiliser_comptes_bancaires",
                    models.BooleanField(
                        default=False,
                        verbose_name="Utiliser la gestion des comptes bancaires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration ERP",
                "verbose_name_plural": "Configuration ERP",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "Client"), ("fournisseur", "Fournisseur")],
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("prix_achat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_vente", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="LigneAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "achat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="erp_app.achat",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("date_facture", models.DateField(auto_now_add=True)),
                ("date_echeance_restant", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("impayée", "Impayée"),
                            ("partielle", "Partiellement payée"),
                            ("payée", "Payée"),
                        ],
                        default="impayée",
                        max_length=20,
                    ),
                ),
                (
                    "achat",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.achat",
                    ),
                ),
                (
                    "commande",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.commande",
                    ),
                ),
                (
                    "achat_lignes",
                    models.ManyToManyField(
                        blank=True, related_name="factures", to="erp_app.ligneachat"
                    ),
                ),
                (
                    "commande_lignes",
                    models.ManyToManyField(
                        blank=True, related_name="factures", to="erp_app.lignecommande"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("espèce", "Espèce"),
                            ("virement", "Virement"),
                            ("chèque", "Chèque"),
                        ],
                        default="espèce",
                        max_length=50,
                    ),
                ),
                ("reference_paiement", models.CharField(blank=True, max_length=100)),
                ("paiement_complet", models.BooleanField(default=True)),
                ("date_echeance_solde", models.DateField(blank=True, null=True)),
                (
                    "compte_bancaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_app.comptebancaire",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.facture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commande",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"type": "client"},
                on_delete=django.db.models.deletion.CASCADE,
                to="erp_app.person",
            ),
        ),
        migrations.AddField(
            model_name="achat",
            name="fournisseur",
            field=models.ForeignKey(
                limit_choices_to={"type": "fournisseur"},
                on_delete=django.db.models.deletion.CASCADE,
                to="erp_app.person",
            ),
        ),
        migrations.CreateModel(
            name="RelancePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField(auto_now_add=True)),
                ("statut", models.CharField(default="envoyée", max_length=20)),
                ("numero", models.PositiveSmallIntegerField(default=1)),
                ("note", models.TextField(blank=True)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="erp_app.facture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("entrée", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_transaction", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_app.comptebancaire",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_app.facture",
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp_app.paiement",
                    ),
                ),
            ],
        ),
    ]
