# Generated by Django 5.1.4 on 2025-06-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenteHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.DateField()),
                ("quantite", models.PositiveIntegerField()),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp_app.produit",
                    ),
                ),
            ],
        ),
    ]
